### ISSUE TITLE
Add demo: DFS with terminal condition

### ISSUE THREAD

**Issue by mattrasto** [mattrasto/phase#34]
A demo displaying the application of a DFS algorithm with a terminal condition (eg. a graph search) should be added. This may be more easily implemented after phase transitions (#27) and state (#30) are implemented.

**Comment by sergeichestakov** [comment]
Finally added a DFS demo and pushed to dev. Adding fancy terminal conditions (e.g tracing the path back from start to goal) should be trivial at this point using the stack and I can get that demo up later if need be.
