### ISSUE TITLE
Add _eventHandlers dictionary to Network object

### ISSUE THREAD

**Issue by mattrasto** [mattrasto/phase#45]
Visualization-wide settings are functionally different from (default) event handlers, and should be contained in a separate dictionary.

Event handlers should interact with the style map as specified in #23. This can be done by wrapping event handlers (default or user-specified) in a higher order function before placing in the _eventHandlers dictionary. The wrapper function will modify the style map before applying the actual style changes.

**Comment by sergeichestakov** [comment]
I moved the event handlers to a separate dictionary in my latest commit. Definitely looks a lot cleaner. Holding off on updating the style map and opening up an API to change event handlers until we decide how to implement that. Will keep the issue open for now.
