### ISSUE TITLE
Separate framework into multiple files

### ISSUE THREAD

**Issue by mattrasto** [mattrasto/phase#50]
The main `phase.js` file is very large now, and it would speed up development (and conform to best practice) to break it into separate files. We should follow the [jQuery](https://github.com/jquery/jquery) approach, where we build each class/utility into a separate file and build/minify it using Grunt or another similar module.

**Comment by sergeichestakov** [comment]
I broke up `phase.js` into 4 separate files and moved them into a `src` directory on the `dev` branch. We can now compile using webpack after we make changes to the source code by running `npm run build` as long as you have the webpack and webpack-cli npm packages installed which you can get by running `npm install`. The compiled and minified file will appear in the `dist` directory which is what we link to in html files. After updating all of the demos, everything seems to be working the same, so if you guys can test it on your system and make sure it works we can merge to master.
