### ISSUE TITLE
Test event handlers demo

### ISSUE THREAD

**Issue by mattrasto** [mattrasto/phase#72]
We should add tests for the event handler demo (`event_handlers.html`). Test plan:

1. Assert that hovering a node changes border of the node (`stroke`) to '#7DABFF' but does not modify its data
2. Assert that hovering a link doesn't change any of its styles or data
3. Click the "Change Hover" button
4. Assert that hovering a node changes border of the node (`stroke`) to 'green'
5. Assert that hovering a node changes the border of the node (`stroke`) to 'green' but does not modify its data
6. Assert that hovering a link changes its width (`stroke-width`) to '3px' and its color (`stroke`) to '#333' but does not modify its data

**Comment by sergeichestakov** [comment]
Implemented in latest commits on dev.
