### ISSUE TITLE
Test morphs demo

### ISSUE THREAD

**Issue by mattrasto** [mattrasto/phase#73]
We should add tests for the morphs demo (`morphs.html`). Test plan:

1. Assert that all nodes' styles are set to default values
2. Assert that all links' styles are set to default values
3. Click the "Apply Morphs" button
4. Assert that the 2 groups are created with the proper values
5. Assert that the 4 morphs are created with the proper values
6. Assert that the nodes in the group have a border (`stroke`) with value '#AE63D4' and a color (`fill`) with value '#7DABFF' and their data's "group" attribute has value "200"
7. Assert that the links in the group have a color (`stroke`) with value '#D46363' and a width (`stroke-width`) with value '3px' and their data's "value" attribute has value "200"
8. Click the "Reset" button
9. Assert that the nodes in the group are reset to their default values
10. Assert that the links in the group are reset to their default values

**Comment by sergeichestakov** [comment]
Fixed in latest commits.
